### ISSUE TITLE
non-ascii string/char issue

### ISSUE THREAD

**Issue by JJins** [Manuito83/torn-pda#188]
```javascript
let str="“test”";
console.log(str); // expect “test”
```

<img width="388" alt="图片" src="https://user-images.githubusercontent.com/5475863/229404108-4b3359ed-c87b-4b35-9a78-0183e63af7fe.png">

It seems `“` char got resolved as `"`.

**Comment by Manuito83** [comment]
Thanks. I actually [changed this a couple of months ago](https://github.com/Manuito83/torn-pda/commit/d9be50baba8f26f11d472fde64e0cf9940660ca7) (see also [here](https://github.com/Manuito83/torn-pda/blob/d9be50baba8f26f11d472fde64e0cf9940660ca7/lib/providers/userscripts_provider.dart#L148)), since some scripts were not working as expected as some users where using both chars interchangeably. Perhaps there is another way around.

**Comment by Kwack-Kwack** [comment]
Unfortunately iOS by default forces users to use `“ ”` instead of `" "`, hence the issues. 

Is there a particular use-case where this is needed but `\u201C` and `\u201D` cannot be used instead? I can't think of one where using the unicode hex code shouldn't be a workaround for the issue here.

**Comment by JJins** [comment]
> as some users where using both chars interchangeably. 

😱 Can't believe that really happened. Ok, not a big thing, I'll replace all these chars to `[]`.

**Comment by JJins** [comment]
> Unfortunately iOS by default forces users to use `“ ”` instead of `" "`, hence the issues.
> 
> Is there a particular use-case where this is needed but `\u201C` and `\u201D` cannot be used instead? I can't think of one where using the unicode hex code shouldn't be a workaround for the issue here.

They looks similar, and `“”` not require escaping, convenient when need to quote something on a string.
