### ISSUE TITLE
Notifications bug

### ISSUE THREAD

**Issue by Robodashy** [Manuito83/torn-pda#82]
Occurs on latest Android version (and other versions rolled out over the last 70 days that I've noticed since I created my account):
In the settings - all notification settings are set to silent or off, yet the notification sound still plays for all events.

Let me know what other information I can provide or if you have any questions regarding this issue.

Love the game, keep up the great work!

**Comment by Manuito83** [comment]
Thanks for that, I'll have a look. All notifications channels are set with priority_max, so that they trigger sound and the notification box, but the user should be able to control this in settings, as you said (at least from API 25 onwards).

What's your Android version? Did you try reinstalling? Also, would you have a look at notifications channels (in the app's information page in Android / Notifications) and see whether there is something being overriden there?

**Comment by Manuito83** [comment]
Could not reproduce, need more info.
